/**
 * Mobile cipher tests (#25, ADR 0033). The load-bearing case is **cross-platform
 * interop**: the vectors below were generated by the web `WebCryptoCipher`
 * (WebCrypto PBKDF2→HKDF→AES-GCM/HMAC) for a fixed phrase. If the noble adapter
 * derives the same `accountId`/`entryId` and decrypts the web ciphertext, then a
 * phrase set up on the web links to the same account and reads the same data on
 * mobile — and vice versa, since AES-GCM is symmetric. A drift here would silently
 * break cross-device sync (different entry ids never merge), so these are pinned.
 */
import { webcrypto } from "node:crypto";
import { beforeAll, describe, expect, it, vi } from "vitest";

// Real randomness for nonces / phrase generation; the cipher imports this seam,
// which would otherwise pull in expo-crypto (unavailable under Node/vitest).
vi.mock("./crypto-random", () => ({
  randomBytes: (n: number) => webcrypto.getRandomValues(new Uint8Array(n)),
  randomId: () => webcrypto.randomUUID(),
}));

import {
  canonicalizeRecoverySecret,
  createNobleCipher,
  generateRecoveryPhrase,
} from "./noble-cipher";
import type { Cipher } from "@ummahlibrary/core";

// --- Reference vectors produced by the WEB cipher for this exact phrase ---
const PHRASE = "MBTQ7-K9XAR-2P4WD-NHJ58-VYZ36";
const KEY = "ul.lastRead";
const PLAINTEXT = '{"surah":18,"ayah":10}';
const ACCOUNT_ID = "2a18292b6de6a845428ce9ffbf5478993b4fd5f3f468cf647890c09efe49be8c";
const ENTRY_ID = "47fb92d7ccf64b6ad6b530daeec67a4e77b9033de692008946f5b704443c057f";
const NONCE_B64 = "CzBVep/E6Q4zWH2i";
const CIPHERTEXT = "NMPO+7NqiblvNSnSsYMFsEFM5eWMZeJXeo5MimMBdmY6UVnUxqo=";

describe("noble-cipher — web interop", () => {
  let cipher: Cipher;
  beforeAll(async () => {
    cipher = await createNobleCipher(PHRASE);
  });

  it("derives the same opaque accountId the web cipher does", async () => {
    expect(await cipher.accountId()).toBe(ACCOUNT_ID);
  });

  it("derives the same entryId (HMAC-SHA256, 64-byte key) the web cipher does", async () => {
    expect(await cipher.entryId(KEY)).toBe(ENTRY_ID);
  });

  it("decrypts ciphertext that the web cipher produced", async () => {
    expect(await cipher.decrypt(CIPHERTEXT, NONCE_B64)).toBe(PLAINTEXT);
  });
});

describe("noble-cipher — local behaviour", () => {
  let cipher: Cipher;
  beforeAll(async () => {
    cipher = await createNobleCipher(PHRASE);
  });

  it("round-trips encrypt → decrypt with a fresh random nonce each time", async () => {
    const a = await cipher.encrypt(PLAINTEXT);
    const b = await cipher.encrypt(PLAINTEXT);
    expect(a.nonce).not.toBe(b.nonce); // fresh IV per call
    expect(a.ciphertext).not.toBe(b.ciphertext);
    expect(await cipher.decrypt(a.ciphertext, a.nonce)).toBe(PLAINTEXT);
    expect(await cipher.decrypt(b.ciphertext, b.nonce)).toBe(PLAINTEXT);
  });

  it("round-trips multi-byte UTF-8 (Arabic) values", async () => {
    const value = '{"note":"السلام عليكم"}';
    const { ciphertext, nonce } = await cipher.encrypt(value);
    expect(await cipher.decrypt(ciphertext, nonce)).toBe(value);
  });

  it("returns null (never throws) on tampered or foreign ciphertext", async () => {
    const { ciphertext, nonce } = await cipher.encrypt(PLAINTEXT);
    const tampered = `${ciphertext.slice(0, -4)}AAAA`;
    expect(await cipher.decrypt(tampered, nonce)).toBeNull();
    expect(await cipher.decrypt("not base64 @@@", nonce)).toBeNull();
    expect(await cipher.decrypt(ciphertext, "bad")).toBeNull();
  });

  it("uses a different account for a different phrase", async () => {
    const other = await createNobleCipher("ZZZZZ-ZZZZZ-ZZZZZ-ZZZZZ-ZZZZZ");
    expect(await other.accountId()).not.toBe(ACCOUNT_ID);
  });
});

describe("recovery secret canonicalization", () => {
  it("derives the SAME account regardless of case, spacing or hyphenation", async () => {
    const a = await createNobleCipher("mbtq7 k9xar 2p4wd nhj58 vyz36");
    const b = await createNobleCipher("MbTq7k9xaR2p4wdNhj58vyz36");
    expect(await a.accountId()).toBe(ACCOUNT_ID);
    expect(await b.accountId()).toBe(ACCOUNT_ID);
  });

  it("strips every non-alphanumeric and upper-cases", () => {
    expect(canonicalizeRecoverySecret("ab-cd ef")).toBe("ABCDEF");
    expect(canonicalizeRecoverySecret("MBTQ7-K9XAR")).toBe("MBTQ7K9XAR");
  });
});

describe("generateRecoveryPhrase", () => {
  it("emits five hyphen-separated groups of five from the safe alphabet", () => {
    const p = generateRecoveryPhrase();
    expect(p).toMatch(/^[ABCDEFGHJKMNPQRSTVWXYZ23456789]{5}(-[ABCDEFGHJKMNPQRSTVWXYZ23456789]{5}){4}$/);
  });

  it("is effectively unique across calls", () => {
    const set = new Set(Array.from({ length: 20 }, () => generateRecoveryPhrase()));
    expect(set.size).toBe(20);
  });
});
