/**
 * Generates the Noor theme CSS from `themes.ts` — the one place CSS custom
 * properties are derived from the palette source of truth (ADR 0027).
 *
 * These pure functions back both the build script (`scripts/build-theme-css.ts`,
 * which writes the committed `.css` files) and the drift test
 * (`theme-css.test.ts`, which asserts the committed files match). Never hand-edit
 * the generated CSS — change `themes.ts` and re-run `build:themes`.
 */
import { noorThemes } from "./themes";
import type { Palette, ThemeKey } from "./themes";

/** Palette field → CSS custom property, in the order they are emitted.
 *  `scheme` is emitted as `color-scheme`; `error` has no CSS var (native-only). */
type CssKey = Exclude<keyof Palette, "scheme" | "error">;
const CSS_TOKENS: ReadonlyArray<readonly [CssKey, string]> = [
  ["bg", "--noor-bg"],
  ["bg2", "--noor-bg2"],
  ["bgElev", "--noor-card"],
  ["cardHi", "--noor-card-hi"],
  ["border", "--noor-border"],
  ["borderSoft", "--noor-border-soft"],
  ["fg", "--noor-fg"],
  ["muted", "--noor-muted"],
  ["faint", "--noor-faint"],
  ["accent", "--noor-gold"],
  ["accentHi", "--noor-gold-hi"],
  ["accentDim", "--noor-gold-dim"],
  ["accentSoft", "--noor-gold-soft"],
  ["accentGrad", "--noor-gold-grad"],
  ["ink", "--noor-ink"],
];

/** Non-themed base fonts (plain fallbacks). The web overrides these with
 *  next/font variables in its own globals.css; standalone hosts use these. */
const BASE_FONTS = [
  '  --noor-ui: "Hanken Grotesk", system-ui, sans-serif;',
  '  --noor-ar: "IBM Plex Sans Arabic", serif;',
].join("\n");

const HEADER = `/* GENERATED by packages/ui/scripts/build-theme-css.ts — do not edit.
   Source of truth: packages/ui/src/themes.ts. Regenerate with
   \`pnpm --filter @ummahlibrary/ui build:themes\` (a drift test guards it). */`;

/** The palette custom-property lines (plus color-scheme) for one theme. */
function paletteBlock(p: Palette): string {
  const lines = CSS_TOKENS.map(([key, cssVar]) => `  ${cssVar}: ${p[key]};`);
  lines.push(`  color-scheme: ${p.scheme};`);
  return lines.join("\n");
}

/** The order of `[data-theme]` blocks after the `:root`/obsidian default. */
const REST: readonly ThemeKey[] = ["midnight", "emerald", "ocean", "ivory", "sepia", "mint", "rose"];

/** Full theme stylesheet: base fonts, the default palette on `:root`, and every
 *  `[data-theme]` block. `ivory` also answers the legacy `light` selector. */
export function renderThemesCss(): string {
  const blocks = [`:root {\n${BASE_FONTS}\n}`, `:root,\n[data-theme="obsidian"] {\n${paletteBlock(noorThemes.obsidian)}\n}`];
  for (const key of REST) {
    const selector =
      key === "ivory" ? '[data-theme="ivory"],\n[data-theme="light"]' : `[data-theme="${key}"]`;
    blocks.push(`${selector} {\n${paletteBlock(noorThemes[key])}\n}`);
  }
  return `${HEADER}\n\n${blocks.join("\n\n")}\n`;
}

/** Obsidian-only `:root` defaults (the design-sync entry + standalone fallback). */
export function renderTokensCss(): string {
  return `${HEADER}\n\n:root {\n${BASE_FONTS}\n${paletteBlock(noorThemes.obsidian)}\n}\n`;
}
