#!/usr/bin/env node
/**
 * Unified dev launcher — used by pnpm dev:web, dev:mobile, and dev:local.
 *
 * Flags:
 *   --web-only          Start only the Next.js web app (port 3000)
 *   --mobile-only       Start only Expo / Metro (port 8081)
 *   --kill              Kill any process on the target port(s) first
 *   --tunnel            Pass --tunnel to Expo (uses ngrok; clears .env.local IP)
 *   --ip <address>      Override auto-detected LAN IP written to .env.local
 */

import { spawn, execFileSync, execSync } from "node:child_process";
import { networkInterfaces } from "node:os";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ENV_PATH = resolve(ROOT, "apps/mobile/.env.local");

const WEB_PORT = 3000;
const METRO_PORT = 8081;

// ── arg parsing ──────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const webOnly = args.includes("--web-only");
const mobileOnly = args.includes("--mobile-only");
const kill = args.includes("--kill");
const tunnel = args.includes("--tunnel");
const ipFlag = args.indexOf("--ip");
const forcedIp = ipFlag !== -1 ? args[ipFlag + 1] : null;

const startWeb = !mobileOnly;
const startMobile = !webOnly;

// ── port killing ─────────────────────────────────────────────────────────────

function killPort(port) {
  const pids = findPids(port);
  if (pids.length === 0) return;
  for (const pid of pids) {
    try { process.kill(pid, "SIGTERM"); } catch { /* already gone */ }
  }
  console.log(`  killed PID${pids.length > 1 ? "s" : ""} ${pids.join(", ")} on :${port}`);
  // wait up to 1 s for the port to be released
  const deadline = Date.now() + 1000;
  while (Date.now() < deadline && findPids(port).length > 0) {
    execSync("sleep 0.1");
  }
}

function findPids(port) {
  // fuser is the most reliable on Linux/WSL
  try {
    const out = execFileSync("fuser", [`${port}/tcp`], { encoding: "utf8", stdio: ["pipe","pipe","pipe"] }).trim();
    return out.split(/\s+/).map(Number).filter(Boolean);
  } catch { /* fuser exits non-zero when nothing is found */ }

  // fallback: lsof (macOS + most Linux)
  try {
    const out = execFileSync("lsof", ["-ti", `tcp:${port}`], { encoding: "utf8" }).trim();
    return out ? out.split("\n").map(Number).filter(Boolean) : [];
  } catch { /* nothing on this port */ }

  return [];
}

if (kill) {
  console.log("→ Freeing ports…");
  if (startWeb) killPort(WEB_PORT);
  if (startMobile) killPort(METRO_PORT);
}

// ── .env.local management (skipped when --web-only) ─────────────────────────

if (startMobile) {
  if (tunnel) {
    writeFileSync(
      ENV_PATH,
      [
        "# Generated by `pnpm dev:local` — do not edit by hand.",
        "# Tunnel mode: EXPO_PUBLIC_API_BASE_URL is intentionally unset.",
        "# Remove this file to revert to the production API.",
        "",
      ].join("\n"),
    );
    console.log("→ Tunnel mode: .env.local cleared (Expo resolves via ngrok URL).");
  } else if (!webOnly) {
    // Only auto-write the IP when both apps start together.
    // --mobile-only leaves .env.local as the developer set it.
    const ip = forcedIp ?? detectLanIp();
    if (!ip) {
      console.error(
        "✗ Could not detect a LAN IP.\n" +
          "  Use --ip <address> or --tunnel, or run `pnpm dev:mobile` and set .env.local manually.",
      );
      process.exit(1);
    }
    const base = writeEnv(ip);
    console.log(`→ Wrote ${ENV_PATH}`);
    console.log(`  EXPO_PUBLIC_API_BASE_URL=${base}`);
  }
}

// ── spawn processes ───────────────────────────────────────────────────────────
// Pass the command as a single string to avoid the DEP0190 warning that
// fires when an args array is combined with shell:true.

const procs = [];

if (startWeb) {
  procs.push(run("pnpm --filter=@ummahlibrary/web dev"));
}

if (startMobile) {
  const cmd = tunnel
    ? "pnpm --filter=@ummahlibrary/mobile dev -- --tunnel"
    : "pnpm --filter=@ummahlibrary/mobile dev";
  procs.push(run(cmd));
}

function run(cmd) {
  return spawn(cmd, { cwd: ROOT, stdio: "inherit", shell: true });
}

function shutdown(signal) {
  for (const p of procs) p.kill(signal);
}

process.on("SIGINT", () => shutdown("SIGINT"));
process.on("SIGTERM", () => shutdown("SIGTERM"));

Promise.all(procs.map((p) => new Promise((res) => p.on("exit", res)))).then(() =>
  process.exit(0),
);

// ── helpers ───────────────────────────────────────────────────────────────────

function detectLanIp() {
  const candidates = [];
  for (const iface of Object.values(networkInterfaces())) {
    for (const addr of iface ?? []) {
      if (addr.family === "IPv4" && !addr.internal) candidates.push(addr.address);
    }
  }
  if (candidates.length === 0) return null;

  // On WSL2 the only non-internal IPv4 is typically the 172.x.x.x virtual
  // adapter, which phones on WiFi cannot reach. Warn and suggest --tunnel.
  const isWsl2 = candidates.every((ip) => ip.startsWith("172."));
  if (isWsl2) {
    console.warn(
      "\n⚠  Running inside WSL2: detected IP " + candidates[0] + " is the WSL2 virtual\n" +
      "   adapter and is not reachable from your phone.\n" +
      "   Use --tunnel for Expo Go, or --ip <windows-host-ip> if you have\n" +
      "   port-forwarding configured on the Windows side.\n",
    );
  }

  return candidates[0];
}

function writeEnv(ip) {
  const base = `http://${ip}:${WEB_PORT}/api/v1`;
  writeFileSync(
    ENV_PATH,
    [
      "# Generated by `pnpm dev:local` — do not edit by hand.",
      "# Delete this file to revert to the production API.",
      `EXPO_PUBLIC_API_BASE_URL=${base}`,
      "",
    ].join("\n"),
  );
  return base;
}
